# 03-01
# Challenge 01 - NumPy katas

![](https://images.unsplash.com/photo-1476525223214-c31ff100e1ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80)
Picture by [Jason Briscoe](https://unsplash.com/photos/HN_4K2diUWs)

In [1]:
# TODO: import the numpy library

In [1]:
import numpy as np

- Create a null array of size 10 but the fifth value which is 1. Your array values should be `int`.

In [4]:
a = np.zeros(10, int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

- Create a vector with values from 10 to 49 and reverse it.

In [138]:
a = np.arange(10, 50)
#a = np.flip(a, 0)
reversed_arr = a[::-1]
reversed_arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

- Create a 3x3 identity matrix.

In [19]:
y = np.zeros((3, 3, 4), int)
y

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

- Create a 3x3 matrix with values ranging from 0 to 8.

In [21]:
a = np.matrix([np.arange(0,9), np.arange(0,9), np.arange(0,9)])
a = np.array([a, a, a])
a


array([[[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]])

- Create an array of size 30 with random integer values from 0 to 5. Find indices of non-zero elements.

In [33]:
a = np.array([np.random.randint(0, 6, 30)])
print(a)
a = np.where(a == 0)
a

[[5 4 5 5 5 4 4 1 4 3 2 0 4 4 5 3 4 1 5 5 1 4 2 3 1 3 1 5 0 4]]


(array([0, 0]), array([11, 28]))

- Create a 10x10 array with random values and find the minimum and maximum values.

In [44]:
a = np.random.randint(0, 101, 100)
a = a.reshape(10,10)
mina = np.amin(a)

maxa = np.amax(a)
maxa
mina

0

- Create a 10x10 2d array with 1 on the border and 0 inside.

In [55]:
a = np.zeros((10,10), int)

a[1:-1, 1:-1] = 1
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

- Create a 10X10 2d array filled with 1's. Add a border (filled with 0's) around.

In [61]:
a = np.ones((10,10), int)
a[1:-1, 1:-1] = 0
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

- Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [65]:
np.tril(np.matrix([np.arange(1,5), np.arange(1,5), np.arange(1,5), np.arange(1,5),np.arange(1,5)]))

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [1, 2, 3, 0],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

- Create a 8x8 matrix and fill it with a checkerboard pattern.

In [72]:
a=np.array(([1,0]*4+[0,1]*4)*4).reshape((8,8))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

- Create a 1D array filled with, 30 random integer values between 1 and 10. Negate all elements which are between 3 and 8, in place.

In [91]:
a = np.random.randint(0, 11, 30)
a[(a<8) & (a>3)] *= -1
a

array([-5, 10,  0, -5,  2, 10,  9,  9, -4,  0,  3, 10,  1, -7, -4,  2,  2,
        0,  1, -4, -4,  0,  0, -6,  0,  2,  0,  3, -5,  2])

- Create random vector of size 10 and replace the maximum value by 0.

In [109]:
a = np.random.randint(0, 11, 30)
a.sort()
a[-1] = 0
a

array([ 1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  4,  4,  4,  4,
        5,  5,  5,  6,  7,  8,  8,  9,  9,  9,  9, 10,  0])

- Subtract the mean of each row of a 5x10 matrix.

In [127]:
a = np.random.randint(1, 100, 50).reshape(10,5)
print("array",  a)
for i in range(len(a)) :
    a[i] -= np.mean(a[i]).astype(int)
a

array [[12 99  1 39 77]
 [78 19 68 71 17]
 [12  4 35 73 90]
 [35 58 26 35 37]
 [49  6 27 42 26]
 [87 10 34 73 67]
 [86 36 44 82 95]
 [95 82 44 69 17]
 [88 78 22 41 48]
 [77 78 59 15 95]]


array([[-33,  54, -44,  -6,  32],
       [ 28, -31,  18,  21, -33],
       [-30, -38,  -7,  31,  48],
       [ -3,  20, -12,  -3,  -1],
       [ 19, -24,  -3,  12,  -4],
       [ 33, -44, -20,  19,  13],
       [ 18, -32, -24,  14,  27],
       [ 34,  21, -17,   8, -44],
       [ 33,  23, -33, -14,  -7],
       [ 13,  14,  -5, -49,  31]])

- Write a function to sort an array by the nth column.

In [129]:
def sort_clolumn(array, n_col):
    return np.concatenate([array[:n_col], np.sort(array[n_col:])])


- Check if a given 2D array has null columns.

In [134]:
a = np.random.randint(1, 100, 25).reshape(5,5)
a[:5, :1] = 0
b = a.T

for i in range(len(b)):
    if np.any(np.where(b[i] == 0)) == True:
        print("null column")


null column


- Swap two rows of an array.

In [147]:
a = np.random.randint(1, 100, 25).reshape(5,5)
print(a)
a[0,:],a[1,:]=a[1,:],a[0,:]
a

temp = A[j,j:n].copy()
A[j,j:n] = A[index,j:n]
A[index,j:n] = temp[:]

[[19  4 91 80 61]
 [37 94 21  1 37]
 [12 45 38 21 94]
 [38 14 70 71 31]
 [94 40 35 52 55]]


array([[37, 94, 21,  1, 37],
       [37, 94, 21,  1, 37],
       [12, 45, 38, 21, 94],
       [38, 14, 70, 71, 31],
       [94, 40, 35, 52, 55]])

- Find the most frequent value in an array.

- Get the n largest values of an array.