# Binary Confusion Matrix 💠

---

![](https://i.pinimg.com/originals/52/6d/94/526d9427a7bfe8b0731a1f5347bcd7b5.jpg)

Photo by [Raw Pixel](https://unsplash.com/@rawpixel)

---

Again, we will explore Winsconsin Breast Cancer data, and dig deeper into the classification results. 🔍

In [3]:
import numpy as np
from sklearn.datasets import load_breast_cancer

np.random.seed(0)
X, y = load_breast_cancer(return_X_y=True)

**Q1**. Split your data into a training set of 80% of the data and a test set of 20%. Specify the `random_state` to 0 so that you get **reproducible** results.

In [4]:
# TODO: Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train, X_test, y_train, y_test

(array([[1.005e+01, 1.753e+01, 6.441e+01, ..., 6.499e-02, 2.894e-01,
         7.664e-02],
        [1.080e+01, 2.198e+01, 6.879e+01, ..., 7.485e-02, 2.965e-01,
         7.662e-02],
        [1.614e+01, 1.486e+01, 1.043e+02, ..., 1.129e-01, 2.778e-01,
         7.012e-02],
        ...,
        [9.436e+00, 1.832e+01, 5.982e+01, ..., 5.052e-02, 2.454e-01,
         8.136e-02],
        [9.720e+00, 1.822e+01, 6.073e+01, ..., 0.000e+00, 1.909e-01,
         6.559e-02],
        [1.151e+01, 2.393e+01, 7.452e+01, ..., 9.653e-02, 2.112e-01,
         8.732e-02]]),
 array([[1.340e+01, 2.052e+01, 8.864e+01, ..., 2.051e-01, 3.585e-01,
         1.109e-01],
        [1.321e+01, 2.525e+01, 8.410e+01, ..., 6.005e-02, 2.444e-01,
         6.788e-02],
        [1.402e+01, 1.566e+01, 8.959e+01, ..., 8.216e-02, 2.136e-01,
         6.710e-02],
        ...,
        [2.018e+01, 1.954e+01, 1.338e+02, ..., 2.173e-01, 3.032e-01,
         8.075e-02],
        [1.831e+01, 2.058e+01, 1.208e+02, ..., 1.510e-01, 3.074e-01,
   

**Q2**. Fit a Logistic Regression on your data. Evaluate accuracy.

In [5]:
# TODO: Logistic Regression

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
score = lr.score(X_test, y_test)
score

/home/wafa/bin/anaconda/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.956140350877193

**Q3**. Now we want to understand better the performance than just the global accuracy. Explore the function `confusion_matrix` of `sklearn`, and use it to display the confusion matrix of your model.

In [6]:
# TODO: Confusion matrix
from sklearn.metrics import confusion_matrix
data = confusion_matrix(y_test, y_pred).T
data

array([[46,  4],
       [ 1, 63]])

**Q4**. Before analyzing it. Let's visualize it more properly (with color, axes label etc.).

- Display the confusion matrix in a more visual way with `seaborn` library

> 🔦 **Hint**: Have a look at `heatmap` from `seaborn` library 

- Verify that your axes are correct

In [82]:
# TODO: Confusion matrix with seaborn
import seaborn as sns
from matplotlib import pyplot as plt
sns.heatmap(data, annot=True, cmap="YlGnBu")
plt.show()

<Figure size 640x480 with 2 Axes>

**Q5**. Compute by hand Precision, Recall and F1_score

In [38]:
TP_FP = (y_pred == 1).sum()
N = (y_pred != 1).sum()

TN_TP = (y_pred == y_test).sum()

TP = ((y_pred == y_test) & (y_pred == 1)).sum()
TP
TN = ((y_pred == y_test) & (y_pred != 1)).sum()
FP = ((y_pred != y_test) & (y_pred == 1)).sum()
FN = ((y_pred != y_test) & (y_pred != 1)).sum()
FN

4

In [40]:
# TODO: Classification metrics
precision = TP/ TP_FP
recall = TP / (FN + TP)

f_score = 2*(precision*recall) / (precision + recall)

precision, recall , f_score

(0.984375, 0.9402985074626866, 0.9618320610687023)

**Q6**. Again, there is a built-in function in `sklearn` in order to compute those scores easily.

It is called `classification_report`. Use it and compare with your previous numbers.

In [9]:
# TODO: classification_report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        47
           1       0.98      0.94      0.96        67

   micro avg       0.96      0.96      0.96       114
   macro avg       0.95      0.96      0.96       114
weighted avg       0.96      0.96      0.96       114



**Q7**. How would you analyze your model performance?

In [12]:
# TODO: classification_report
